# dnsmasq-server/Dockerfile
#      "--pxe-service=x86PC,'Network Boot',ipxe.efi"
#    "--pxe-service=X86-64_EFI,'Network Boot UEFI',ipxe.efi"]
# "--dhcp-match=set:ipxe,175,24"

FROM docker.io/debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends dnsmasq \
    && rm -rf /var/lib/apt/lists/*
CMD ["dnsmasq", \
     "--no-daemon", \
     "--port=0", \
     "--log-queries", \
     "--log-dhcp", \
     "--enable-tftp", \
     "--tftp-root=/srv/tftp", \
     "--tftp-no-blocksize", \
     "--dhcp-range=192.168.1.254,proxy", \
     "--dhcp-userclass=set:ipxe,iPXE", \
     "--pxe-service=tag:!ipxe,X86-64_EFI,'Network Boot',ipxe.efi", \
     "--pxe-service=tag:!ipxe,x86PC,'Network Boot',undionly.kpxe", \
     "--dhcp-boot=tag:ipxe,http://192.168.1.95:8080/boot.ipxe,,192.168.1.95"]
