all:
  children:
    proxmox:
      hosts:
        node1:
          ansible_host: node1.pve.local
      vars:
        ansible_python_interpreter: /nix/store/f2krmq3iv5nibcvn4rw7nrnrciqprdkh-python3-3.12.9/bin/python3
