- name: Setup automation users
  hosts: proxmox
  gather_facts: false
  connection: local
  vars_prompt:
    - name: root_password
      prompt: "Proxmox root password"
      private: true

    - name: terraform_prov_password
      prompt: "Password for terraform-prov user"
      private: true
      confirm: true

    - name: ansible_password
      prompt: "Password for terraform-prov user"
      private: true
      confirm: true
  module_defaults:
    group/community.proxmox.proxmox:
      api_host: "{{ ansible_host }}"
      api_user: root@pam
      api_password: "{{ root_password }}"
      validate_certs: false
  roles: 
    - role: create_pve_user
      vars: 
          playbook_user: root@pam
          playbook_password: root_password
          pve_user: "terraform-prov@pve"
          pve_role: "TerraformProv"
          pve_user_password: "{{ terraform_prov_password }}"
          pve_privileges:
            - VM.Allocate
            - Datastore.Audit
            - VM.Config.CPU
            - SDN.Use
            - VM.Clone
            - Pool.Allocate
            - Datastore.Allocate
            - Datastore.AllocateSpace
            - VM.Config.Options
            - VM.PowerMgmt
            - Datastore.AllocateTemplate
            - VM.Config.HWType
            - VM.Config.CDROM
            - Sys.Console
            - Sys.Audit
            - VM.Audit
            - Sys.Modify
            - VM.GuestAgent.Audit
            - VM.Migrate
            - VM.Config.Cloudinit
            - VM.Config.Memory
            - VM.Config.Disk
            - VM.Config.Network
            - VM.Console    
