---
- name: Setup automation users
  hosts: proxmox
  gather_facts: false
  connection: local
  module_defaults:
    group/community.proxmox.proxmox:
      api_host: "{{ ansible_host }}"
      api_user: root@pam
      api_password: "{{ sops.root_password }}"
      validate_certs: false
  roles: 
    - role: configure_opnsense_backup_job
      vars: 
          playbook_user: root@pam
          backup_script_dest: /usr/local/bin/opnsense-backup
          backup_env_dest: /etc/opnsense-backup.env
          backup_dir: /opt/opnsense-backup/repo
          deploy_key_dest: /root/.ssh/git_deploy_key
          cron_log: /var/log/opnsense-backup.log    
