---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    roles-path: "${HOME}/.ansible/collections/"


driver:
  name: molecule-proxmox
  options:
    api_host: "${MOLECULE_PROXMOX_API}"
    api_user: "${MOLECULE_PROXMOX_USER}"
    api_token_id: "${MOLECULE_PROXMOX_TOKEN_ID}"
    api_token_secret: "${MOLECULE_PROXMOX_TOKEN_SECRET}"
    node: "${MOLECULE_PROXMOX_NODE}"
    ssh_user: "${MOLECULE_PROXMOX_USER}"
    ssh_identity_file: "${MOLECULE_SSH_IDENTITY_FILE}"

platforms:
  - name: test-prov-user
    template_name: "${MOLECULE_PROXMOX_TEMPLATE}"
    ciuser: ansible
    sshkeys: "${MOLECULE_SSH_PUBLIC_KEY}"
    ipconfig:
      ipconfig0: "ip=dhcp"
    nameservers:
      - "${MOLECULE_PROXMOX_DNS}"

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${PROJECT_PATH}/ansible_roles/create_pve_user/../"
  inventory:
    group_vars:
      all: 
        proxmox_host: "${MOLECULE_PROXMOX_HOST}"
        pve_api_base: "${MOLECULE_PROXMOX_API}"
        pve_user: "terraform-prov@pve"
        pve_role: "TerraformProv"
        playbook_user: "root@pam"
        playbook_password: "${PROXMOX_ROOT_PASSWORD}"
        root_password: "${PROXMOX_ROOT_PASSWORD}"
        terraform_user: "terraform-prov@pve"
        pve_privileges:
          - VM.Allocate
          - Datastore.Audit
          - VM.Config.CPU
          - SDN.Use
          - VM.Clone
          - Pool.Allocate
          - Datastore.Allocate
          - Datastore.AllocateSpace
          - VM.Config.Options
          - VM.PowerMgmt
          - Datastore.AllocateTemplate
          - VM.Config.HWType
          - VM.Config.CDROM
          - Sys.Console
          - Sys.Audit
          - VM.Audit
          - Sys.Modify
          - VM.GuestAgent.Audit
          - VM.Migrate
          - VM.Config.Cloudinit
          - VM.Config.Memory
          - VM.Config.Disk
          - VM.Config.Network
          - VM.Console
        
verifier:
  name: ansible
