- import_playbook: register-nodes.yaml

- name: Setup automation users
  hosts: proxmox
  gather_facts: false
  connection: local
  module_defaults:
    group/community.proxmox.proxmox:
      api_host: "{{ ansible_host }}"
      api_user: root@pam
      api_password: "{{ root_password }}"
      validate_certs: false
  roles: 
    - role: create_pve_user
      vars: 
          ansible_python_interpreter: "/usr/bin/env python3"
          pve_api_base: 'https://{{ ansible_host }}:8006/api2/json'
          playbook_user: root@pam
          playbook_password: '{{ root_password }}'
          pve_user: "terraform-prov@pve"
          pve_role: "TerraformProv"
          pve_user_password: "{{ terraform_prov_password }}"
          terraform_user: "terraform-prov@pve"
          pve_privileges:
            - VM.Allocate
            - Datastore.Audit
            - VM.Config.CPU
            - SDN.Use
            - VM.Clone
            - Pool.Allocate
            - Datastore.Allocate
            - Datastore.AllocateSpace
            - VM.Config.Options
            - VM.PowerMgmt
            - Datastore.AllocateTemplate
            - VM.Config.HWType
            - VM.Config.CDROM
            - Sys.Console
            - Sys.Audit
            - VM.Audit
            - Sys.Modify
            - VM.GuestAgent.Audit
            - VM.Migrate
            - VM.Config.Cloudinit
            - VM.Config.Memory
            - VM.Config.Disk
            - VM.Config.Network
            - VM.Console    
